## **Basic numpy syntaxes**

In [2]:
import numpy as np

#### **Information**

In [36]:
def info(a, end="\n------------------------\n"):
    print(f'type={type(a)}')
    print(f'size={a.size}')
    print(f'shape={a.shape}')
    print(a, end=end)

**What a numpy array have?**
- Attributes:
    - ndim: number of dimensions
    - size: number of elements
    - shape: shape
    - dtype: data type


##### Create an array and print it

In [37]:
# 0-D array
arr = np.array(1)
info(arr)

# 1-D array
arr = np.array([1, 2, 3])
info(arr)

# 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
info(arr)

# 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
info(arr)



type=<class 'numpy.ndarray'>
size=1
shape=()
1
------------------------
type=<class 'numpy.ndarray'>
size=3
shape=(3,)
[1 2 3]
------------------------
type=<class 'numpy.ndarray'>
size=6
shape=(2, 3)
[[1 2 3]
 [4 5 6]]
------------------------
type=<class 'numpy.ndarray'>
size=12
shape=(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------------------------


##### Check Number of Dimensions

In [38]:
print(arr.ndim)

3


#### **Indexing**
- arr[index]
- index can be negative or slicing

In [40]:
# Get the second element
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1])


# Get the element in 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 0])

2
4


#### **Slicing**

start:end:step
- start: default is 0
- end: excluded, default is the number of elements in the current dimensions
- step: default is 1
- can be negative number



In [43]:
arr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
print(arr[2:5])


[7 6 5]
